server:
  port: 7260

spring:
  application:
    name: security-reactive
  security.user:
    name: marcin
    password: marcin
    roles: manager

# For tests
logging.level.org.springframework.cloud.sleuth: DEBUG
