spring:
  application:
    name: cassandra

spring.data.cassandra:
  keyspace-name: example
  schema-action: recreate
  local-datacenter: datacenter1

# For tests
logging.level.org.springframework.cloud.sleuth: DEBUG
