spring:
  application:
    name: cassandra-reactive
# TODO: Breaks context propagation if set
#  sleuth:
#    reactor:
#      instrumentation-type: decorate_queues

spring.data.cassandra:
  keyspace-name: example
  schema-action: recreate
  local-datacenter: datacenter1

# For tests
logging.level.org.springframework.cloud.sleuth: DEBUG
